### ISSUE TITLE
LICENSE mismatch

### ISSUE THREAD

**Issue by jcdubois** [snakehand/heatshrink#2]
The LICENSE file in the git repository states that the software is under "BSD 2-Clause License".

However the Cargo.toml file of the project (the one used in crates.io) states that the license is ""MIT OR Apache-2.0"".

Which is right?

This discrepancy needs to be resolved.

**Comment by snakehand** [comment]
Dual licensing is fine for me, and I have not paid much attention to this. You are welcome to make a PR to fix this.

**Comment by jcdubois** [comment]
PR is sent.

**Comment by snakehand** [comment]
PR is merged. I will make new release after I have fixed the other outstanding issue.
